services:
  cstimer:
    build:
      context: ../
      dockerfile: Docker/Dockerfile
    ports:
      - "8080:80" # Map port 8080 on the host to port 80 in the container
      - "8888:443"
      - "9000:9000"
    volumes:
      - ../:/cstimer